### PR TITLE
Fix/gossip breaking changes

### PR DESCRIPTION
**Pull request by toblut-midmug**
Bumped [gossip.hoon](https://github.com/Fang-/suite/blob/master/lib/gossip.hoon) to version `v1.1.0` and updated [/lib/pals.hoon](https://github.com/Fang-/suite/blob/master/lib/pals.hoon). This should make the app compatible with the current `%pals` version.

### CODE REVIEW

**Review by marcusmiguel — CHANGES_REQUESTED** [review]
I had to update the `%json` mark to get it working properly: 
```
::
::::  /hoon/json/mar
  ::
/?    310
  ::
::::  compute
  ::
=,  eyre
=,  format
=,  html
|_  jon=^json
::
++  grow                                                ::  convert to
  |%
  ++  mime  [/application/json (as-octs:mimes -:txt)]   ::  convert to %mime
  ++  txt   [(en:json jon)]~
  --
++  grab
  |%                                                    ::  convert from
  ++  mime  |=([p=mite q=octs] (fall (de:json (@t q.q)) *^json))
  ++  noun  ^json                                        ::  clam from %noun
  ++  numb  numb:enjs
  ++  time  time:enjs
  --
++  grad  %mime
--
```

**Comment by toblut-midmug** [comment]
> I had to update the %json mark to get it working properly:

Hmm. What error do you get? It works on my moon ™ with kernel version `p8b1a`. Weirdly, the `%base` desk seems to have the (latest?) `json` mark you posted while the `%webterm` desk does not. I am starting to think that excluding all the "dependencies" might have been a mistake. What do you think?

**Comment by MarcusMiguel** [comment]
When i try to submit any action in the frontend, I get:
```
/mar/json/hoon::[11 9].[11 13]>
/mar/json/hoon::[11 5].[11 13]>
/mar/json/hoon::[11 1].[26 3]>
/mar/json/hoon::[10 1].[26 3]>
/mar/json/hoon::[9 1].[26 3]>
/mar/json/hoon::[8 1].[26 3]>
[%error-building /mar/json/hoon]
[%error-building-cast %json %classifieds-action]
[%error-building-tube %json %classifieds-action]
```

**Comment by toblut-midmug** [comment]
> When i try to submit any action in the frontend, I get: [...]

Oh - good catch. Yeah I get the same. On `~dister-toblut-midmug`, I have updated (i.e. copied) the following files, this time from `%base`:

* `/mar/json.hoon`
* `/mar/json/rpc/response.hoon`

It should work now...

> I don't know how this works. When you don't add the marks, is it supposed to get dependencies from %base?

Well, I basically followed [these](https://github.com/MarcusMiguel/classifieds#install-the-agent) steps, i.e. just copied the `%webterm` desk and added the files from this repo. 

I don't know of a good way to do dependency management for urbit apps -  perhaps adding symlinks (e.g. like [here](https://github.com/uqbar-dao/dev-suite/tree/master/lib)) would be a good way. I have created an [issue](https://github.com/MarcusMiguel/classifieds/issues/12) - please have a look.

**Comment by toblut-midmug** [comment]
> I have created an [issue](https://github.com/MarcusMiguel/classifieds/issues/12) - please have a look.

If you agree, I can do this as part of this PR.

**Comment by MarcusMiguel** [comment]
`%webterm` was removed from the urbit repo and now has its own repo (maybe thats why it's outdated). Idk if the work of adding symliks is worth, maybe we can just change the README tutorial to use `%base` (if that includes all dependencies) or other desk.

**Comment by toblut-midmug** [comment]
`%base` is missing `mar/docket-0.hoon` for some strange reason. But `%garden` seems to work!

**Review by marcusmiguel — APPROVED** [review]
Thanks!

**Pull request merged**
