### PR TITLE
Feature/interface responsiveness

### PR DESCRIPTION
**Pull request by MarcusMiguel**
##  Changes
- Bumped the version to 0.0.2.
- Increase images limit to 20.
- Interface working on smaller screens.

Screenshot_17

### CODE REVIEW

**Review by toblut-midmug — COMMENTED** [review]
Awesome! It's way smoother now. I just noticed that a user's own ads get listed under "Ads" as well - not just under "My ads". Was this intentional?

**Comment by MarcusMiguel** [comment]
it's probably a bug, i will check it out

**Comment by MarcusMiguel** [comment]
Can you give more details about when this happens? To me its working as expected (just some delay when transitioning between tabs, the delay gets significant if i simulate a slower device).

**Comment by toblut-midmug** [comment]
I am also struggling to reproduce it. I deleted the "candle" ad from "My Ads". It gets removed from "My Ads" and also from the "Ads" view of peers. But it still shows up under "Ads" of the publisher. Persists after re-opening the app / reloading the fronted. I'll do a more thorough check tomorrow.

image

**Comment by MarcusMiguel** [comment]
I think it's a backend issue, you're probably getting your own gossip somehow and saving it to ads.

**Comment by toblut-midmug** [comment]
Yeah backend for sure. Still cannot reproduce it but I checked the state.

**Pull request merged**
